select filetype_name,       
SUM(SMALL_READ_REQS) sum_SMALL_READ_REQS,                
           
SUM(SMALL_SYNC_READ_REQS) sum_SMALL_SYNC_READ_REQS,      
SUM(LARGE_READ_REQS) sum_LARGE_READ_REQS,                
             
SUM(SMALL_READ_SERVICETIME) sum_SMALL_READ_SERVICETIME,  

SUM(SMALL_SYNC_READ_LATENCY) sum_SMALL_SYNC_READ_LATENCY,
SUM(LARGE_READ_SERVICETIME) sum_LARGE_READ_SERVICETIME,  
SUM(LARGE_WRITE_SERVICETIME) sum_LARGE_WRITE_SERVICETIME 
from v$iostat_file 
group by filetype_name 
